name: first CI pipeline
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: say Hello
        run: echo "Hello, World!"
    
      - name: Run script
        run: python app.py