name: build docker image
on:
  push:
  
job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t lakshya.app .

      - name: images
        run: docker images